### ISSUE TITLE
Problème de cooldown pour les invocations

### ISSUE THREAD

**Issue by Feulito** [Auraylien/cookie-bot-public#1]
# Le problème (vraiment très gros)

Quand j'ai fait une invocation, le programme me dit d'attendre 17h08 car j'ai déjà fait une invocation à 17h03.
J'ai donc attendu 18h08, et ait relancé une invocation. **Il m'a encore dit d'attendre 17h08 alors qu'il EST 17h08 !!**

<img width="298" alt="image" src="https://user-images.githubusercontent.com/45440448/228284296-0d05e426-2a69-4187-bd18-13ef739b653b.png">

# Solution (Vraiment toute bête)

IL FAUT AFFICHER LES SECONDES POUR EVITER TOUTE ABIGUITE !!

# Comment faire ? (Faut vraiment tout expliquer)

FAUT RAJOUTER UN %s COMME NOUS EN AVONS CONVENU PAR ORAL :).

**Comment by Feulito** [comment]
Bon, j'ai édité les horaires car je me suis trompé

**Comment by antoinealexisb** [comment]
c'est une bonne remarque, nous pouvons faire des MR avec le fix ?

**Comment by Feulito** [comment]
Merci beaucoup pour cet ajout de précision !
